package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

import javafx.scene.canvas.Canvas;

public class SampleController {
	@FXML
	private Canvas myCanvas;
	@FXML
	private Button btnClear;
	@FXML
	private Button btnTestDraw;

	// Event Listener on Button[#btnClear].onMouseClicked
	@FXML
	public void onBtnClearClick(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnTestDraw].onMouseClicked
	@FXML
	public void onBthTestDrawClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
