package application;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;

public class SampleController implements Initializable {
	@FXML
	private Canvas myCanvas;
	private GraphicsContext gc;
	@FXML
	private Button btnClear;
	@FXML
	private Button btnTestDraw;

	// Event Listener on Button[#btnClear].onMouseClicked
	@FXML
	public void onBtnClearClick(MouseEvent event) {
		// TODO Autogenerated
		gc.setFill(Color.BLACK);
		gc.fillRect(5, 5, 590, 590);
	}
	// Event Listener on Button[#btnTestDraw].onMouseClicked
	@FXML
	public void onBthTestDrawClick(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		gc=myCanvas.getGraphicsContext2D();
		gc.setFill(Color.AZURE );
		gc.fillRect(5, 5, 590, 590);
	}
}
