package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseDragEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.canvas.Canvas;

import javafx.scene.input.DragEvent;
import javafx.scene.input.MouseButton;

public class SampleController {
	@FXML
	private Canvas CanvFX;
	@FXML
	private Button but;
	
	@FXML
	public void onMouseD(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("MouseD"+event.getButton().toString());
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void onMonkey(MouseEvent event) {
		// TODO Autogenerated
		if(event.getButton()==MouseButton.PRIMARY){
			System.out.println("LeftMonkey");
		}
		if(event.getButton()==MouseButton.SECONDARY){
			System.out.println("RightMonkey");
		}
	}
	// Event Listener on Canvas[#CanvFX].onDragDetected
	@FXML
	public void onDDetected(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("DragDet");
		try{
		System.out.printf("X=%d Y=%d",event.getX(),event.getY());
		}catch( Exception e){
			e.printStackTrace();
		}
		
	}
	// Event Listener on Canvas[#CanvFX].onDragDone
	@FXML
	public void onDDone(DragEvent event) {
		// TODO Autogenerated
		System.out.println("DragDone");
	}
	// Event Listener on Canvas[#CanvFX].onDragOver
	@FXML
	public void onDOver(DragEvent event) {
		// TODO Autogenerated
		System.out.println("Drag");
	}
	// Event Listener on Button[#but].onMouseClicked
	@FXML
	public void onBut(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("ButClick");
	}


}
