package application;

import javafx.fxml.FXML;
import javafx.geometry.VPos;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.Slider;

import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.TextAlignment;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;

public class MyGraphController {
	@FXML
	private Canvas Canv;
	@FXML
	private Button Btn1;
	@FXML
	private Slider SHor;
	@FXML
	private Slider SVer;
	@FXML
	private TextField txtH;
	@FXML
	private TextField txtV;
	Double dkH = 300.;
	Double dkV = 300.;
	// Event Listener on Button[#Btn1].onMouseClicked
	@FXML
	public void OnBtn1(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Slider[#SHor].onMouseDragged
	@FXML
	public void onScrollH(MouseEvent event) {
		// TODO Autogenerated
		
		dkH = SHor.getValue();
		txtH.setText(dkH.toString());
		Coord(dkH,dkV,Canv.getGraphicsContext2D());
	}
	// Event Listener on Slider[#SVer].onMouseDragged
	@FXML
	public void onMouseDragV(MouseEvent event) {
		// TODO Autogenerated
		
		dkV = SVer.getValue();
		txtV.setText(dkV.toString());
		Coord(dkH,dkV,Canv.getGraphicsContext2D());
		
	}
	
	
	public void Coord(double x0,double y0,GraphicsContext gc){
		
		gc.setFill(Color.BLACK);
		gc.fillRect(0, 0, 598, 598);
		
		gc.setFill(Color.LIGHTGREEN);
		gc.setStroke(Color.LIGHTGREEN);
		gc.setLineWidth(1);
		// CoordSystem
		gc.strokeLine(0,y0 , 560, y0);
		gc.strokeLine(x0, 30, x0, 598);
		gc.strokeLine(x0, 30, x0+5, 40);
		gc.strokeLine(x0, 30, x0-5, 40);
		gc.strokeLine(550,y0+5 , 560, y0);
		gc.strokeLine(550,y0-5 , 560, y0);
		
		
		gc.setFont(Font.font ("Verdana", 20));
//		gc.fillText("X", 562, 0);

		
		gc.setTextAlign(TextAlignment.CENTER);
        gc.setTextBaseline(VPos.CENTER);
//        gc.fillText(
//            "Text centered on your Canvas", 
//            Math.round(Canv.getWidth()  / 2), 
//            Math.round(Canv.getHeight() / 2)
//        );
        gc.setFill(Color.GHOSTWHITE);
        gc.fillText("X", 578,dkV );
        gc.fillText("Y", dkH,10 );
        gc.fillText("o", dkH-13,dkV+13 );
		}

}
