package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class ConstrController {
	@FXML
	private TextField p1;
	@FXML
	private TextField p2;
	@FXML
	private TextField p3;
	@FXML
	private TextField p4;
	@FXML
	private TextField p5;
	@FXML
	private Button btnCalc;

	// Event Listener on Button[#btnCalc].onMouseClicked
	@FXML
	public void btnCalcClick(MouseEvent event) {
		// TODO Autogenerated
	}
}
