package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class ConstrController {
	@FXML
	private TextField p1;
	@FXML
	private TextField p2;
	@FXML
	private TextField p3;
	@FXML
	private TextField p4;
	@FXML
	private TextField p5;
	@FXML
	private Button btnCalc;

	// Event Listener on Button[#btnCalc].onMouseClicked
	@FXML
	public void btnCalcClick(MouseEvent event) {
		// TODO Autogenerated
		Integer i1,i2,i3,sum;
		String Buf;
		i1 = Integer.valueOf(p1.getText());
		i2 = Integer.valueOf(p2.getText());

		/*
		if(i1>i2){
			Buf = "Первое больше";
		} else if(i1==i2) {
			Buf = "Они равны";	
		} else {
			
			Buf = "Первое меньше";
		}
	
		sum = 0;
		for(i3=i1;i3<=i2;i3++){
			sum = sum+i3;			
		}
		*/		
		//i3 = i1 % 2;
	
		Integer from,to;
		from = i1;
		if(from % 2 != 0){
			from++;
		} 
		to = i2;
		
		sum = 0;
		for(i3=from;i3<=to;i3=i3+2){
			sum = sum+i3;
		}
		
		
		p3.setText(sum.toString());
	}
}
